version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: fideruser
      POSTGRES_PASSWORD: fiderpass
      POSTGRES_DB: fiderdb
    volumes:
      - fider-db:/var/lib/postgresql/data

  fider:
    build: .
    image: fider-local
    restart: always
    depends_on:
      - db
    environment:
      BASE_URL: https://millorem.ripollet.cat
      JWT_SECRET: "jwt_s3cr3t$25"
      DATABASE_URL: "postgres://fideruser:fiderpass@db:5432/fiderdb?sslmode=disable"
      EMAIL_SMTP_HOST: mailhost.ripollet.cat
      EMAIL_SMTP_PORT: 25
      EMAIL_NOREPLY: noreply@ripollet.cat
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fider.rule=Host(`millorem.ripollet.cat`)"
      - "traefik.http.routers.fider.entrypoints=websecure"
      - "traefik.http.routers.fider.tls=true"

volumes:
  fider-db:

networks:
  web:
    external: true

